### ISSUE TITLE
flatMap method?

### ISSUE THREAD

**Issue by pitaj** [RobertWHurst/relign#2]
I've always thought that `flatMap` is super useful as a general programming concept. It's especially useful for filterMapping. I hate using `.filter(Boolean)` at every corner. 

One tough decision is whether to accept `undefined` and `null` as true values, or to skip over them.

**Comment by RobertWHurst** [comment]
I've implemented a flat map implementation as per your suggestion.

`v0.9.0` implements `parallelFlatMap` and `seriesFlatMap`, both of which handle arrays or objects.

Examples:
```javascript
// Array of items
parallelFlatMap([1, 2, 3], (n) => {
  if (n === 2) { return; }
  return [n, n + 1];
}).then((r) => assert.deepEqual(r, [1, 2, 3, 4]));

// Object of items
parallelFlatMap({ a: 1, b: 2, c: 3 }, (n, k) => {
  if (k === 'b') { return; }
  return { [`${k}1`]: n, [`${k}2`]: n + 1 };
}).then((r) => assert.deepEqual(r, { a1: 1, a2: 2, c1: 3, c2: 4 }));

// A simple example
parallelFlatMap([1, 2, 3], n => n !== 2 ? [n + 1] : [])
  .then(r => assert.deepEqual(r, [2, 4]));
```

Let me know what you think 🍻

**Comment by pitaj** [comment]
Is there a limit version for these methods?
