### ISSUE TITLE
Simplified API

### ISSUE THREAD

**Issue by pitaj** [RobertWHurst/relign#3]
I love this library (especially the `auto` method!), but the API is kinda long-winded. I think a couple changes could make it much simpler and easier to use.

- For `xxLimit` methods, the limit could be just another parameter in the main method. Ex:
  `relign.parallelLimit(tasks, limit) ==> relign.parallel(tasks, limit)`
- Series methods are generally used less than parallel methods. I think adding the series method as a property of the original method could reduce typing significantly. Ex:
  `relign.parallelFind ==> relign.find`
  `relign.seriesFind ==> relign.find.series`

Some other suggestions:

- `exec` could accept node-style functions by inspecting `Function.prototype.length`. If the length is 2, it's a function that receives a callback.
- `exec` could accept generator functions by inspecting `Function.prototype.toString()`. If it's a generator function, use an algorithm like **`co`** to convert it into an async function.
- Implement a `class Relign extends Promise` which could wrap any of the values accepted by `exec` and would have a bunch of instance methods based on relign's methods. Any `.then` would return a `new Relign` object, as well as the static `Relign` methods.

Let me know what you think of my ideas. I like this library enough that I'm willing to contribute any of these changes if you'd appreciate my help.

**Comment by RobertWHurst** [comment]
Good ideas 👍 

I've taken on your suggestions for exec behavior. v0.10.0 exec can now handle callbacks like async, and generators, collecting all values yielded into an array. Let me know what you think.

**Comment by pitaj** [comment]
Hmmm... I think what you were thinking with generators is different from what I was thinking. I was thinking  something like https://github.com/tj/co, which treats generators like `async/await`, using `yield` as `await`.

**Comment by RobertWHurst** [comment]
I think I get what you mean, but just to be sure, can you give me an example of how you'd expect exec to work?

**Comment by pitaj** [comment]
```js
exec(function* genFn() {
  const joe = yield getUser('joe');

  const posts = yield getPosts(joe.id);

  return joe.age;
}).then(joeAge => {});
```

Where `getUser` and `getPosts` return a Promise. It's essentially just async/await.

**Comment by RobertWHurst** [comment]
I see what you mean. It's my feeling it's better to use co for this should you need it. Additionally, with async await, this feature might not make much sense in the long term. I assumed treating the generator as a set would be better.

_Your example but with async await:_
```js
exec(async function genFn() {
  const joe = await getUser('joe');

  const posts = await getPosts(joe.id);

  return joe.age;
}).then(joeAge => {});
```
